### PR TITLE
A slightly more noticeable cover and a less gigantic title

### PR DESCRIPTION
**Pull request by e-shl**
| before | after |
| ------- | ------- |
| image | image |

### CODE REVIEW

**Comment by CrepeTF** [comment]
I can accept the higher alpha for the backdrop but I won't accept reduce the size buttons and text

**Comment by e-shl** [comment]
> size text

but he's always too gigantic, only two (almost one) words can fit
> size buttons

not critically (I can remove)

**Comment by e-shl** [comment]
| 1 | 2 |
| ------- | ------- |
|  |  | 

that's what it is?

**Comment by CrepeTF** [comment]
Making the title smaller is not negotiable, it's important to the UI

**Comment by e-shl** [comment]
> Making the title smaller is not negotiable, it's important to the UI

I just wanted to show. In general, the main thing in this pull is the cover. And I didn't want to shorten the title so much, but the source does not have a font between 4 and 5

**Pull request closed without merging**
